import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 23

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_title = true
dynamic_padding = true
resize_increments = true
decorations_theme_variant = "Dark"

[window.padding]
x = 0
y = 0 

[env]
TERM = "xterm-256color"
