import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
size = 22 

[font.normal]
family = "FiraMono Nerd Font Mono"

[font.bold]
family = "FiraMono Nerd Font"

[window]
dynamic_title = false
dynamic_padding = true

[window.padding]
x = 0
y = 0

# [env]
# TERM = "xterm-256color"
