import = [
#"~/.config/alacritty/rose-pine.toml"
"~/.config/alacritty/catppuccin-latte.toml"]

[font]
size = 20 

[font.normal]
family = "FiraMono Nerd Font Mono"

[font.bold]
family = "FiraMono Nerd Font Mono"

[window.padding]
x = 0
y = 0

[env]
TERM = "screen-256color"
