# import = ["~/.config/alacritty/catppuccin-mocha.toml"]
# import = [ "~/.config/alacritty/themes/themes/blood_moon.toml" ]
# import = [ "~/.config/alacritty/themes/themes/hyper.toml" ]
# import = [ "~/.config/alacritty/themes/themes/rose-pine.toml" ]
import = [ "~/.config/alacritty/themes/themes/github_dark.toml" ]
# import = [ "~/.config/alacritty/themes/themes/gruvbox.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 19

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGL Nerd Font"
# family = "FiraMono Nerd Font"
# family = "FiraMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
# family = "FiraCode Nerd Font"
family = "GeistMono Nerd Font"

[font.bold]
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGL Nerd Font" 
# family = "FiraMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
# family = "FiraCode Nerd Font"
family = "GeistMono Nerd Font"

[font.italic]
# family = "JetBrainsMono Nerd Font"
# family = "MesloLGL Nerd Font"
# family = "FiraMono Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
# family = "FiraCode Nerd Font"
family = "GeistMono Nerd Font"

[window]
dynamic_title = true
dynamic_padding = true
# resize_increments = true
decorations_theme_variant = "Dark"
decorations = "Buttonless"
# decorations = "Full"
# opacity = 0.95
# blur = true

[window.padding]
x = 0
y = 0 

[colors.primary]
# background = "#000000"
background = "#0D1117"

[colors.cursor]
text = "#000000"
cursor = "#ffffff"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Backspace", mods = "Alt", chars = "\u001B\u007F" },
  { key = "Backspace", mods = "Command", chars = "\u0015" },
  { key = "Left",  mods = "Command", chars = "\u001BOH", mode = "AppCursor" },
  { key = "Right", mods = "Command", chars = "\u001BOF", mode = "AppCursor" },
]

[mouse]
hide_when_typing = true
